# Generated by Django 4.1.4 on 2023-04-20 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0003_lists_user'),
        ('my_travels', '0017_alter_places_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('trip_details', models.TextField(blank=True)),
                ('journey_details', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('lists', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lists.lists')),
                ('places', models.ManyToManyField(blank=True, to='my_travels.places')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
