# Generated by Django 4.1.4 on 2023-04-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_lists_user'),
        ('my_travels', '0017_alter_places_tag'),
        ('trip_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='lists',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.lists'),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='places',
            field=models.ManyToManyField(blank=True, null=True, to='my_travels.places'),
        ),
    ]
