# Generated by Django 4.1.4 on 2023-08-26 07:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_travels', '0018_alter_places_description'),
        ('trip_plans', '0003_rename_journey_details_tripplan_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='tag',
            field=models.ManyToManyField(blank=True, to='my_travels.tag'),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
