# Generated by Django 4.1.4 on 2023-12-07 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip_plans', '0004_tripplan_tag_alter_tripplan_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
