# Generated by Django 4.1.4 on 2023-01-02 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_travels', '0002_placesvisited_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesvisited',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placesvisited',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
