# Generated by Django 4.1.4 on 2023-01-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_travels', '0003_placesvisited_user_alter_placesvisited_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesvisited',
            name='description',
            field=models.TextField(),
        ),
    ]
