# Generated by Django 4.1.4 on 2023-01-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_travels', '0006_userconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserConfig',
        ),
    ]
