# Generated by Django 4.1.4 on 2023-01-28 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_travels', '0007_delete_userconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlacesVisited',
            new_name='Places',
        ),
    ]
