# Generated by Django 4.1.4 on 2023-01-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_travels', '0008_rename_placesvisited_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='group',
            field=models.CharField(choices=[('AV', 'Already Visited'), ('WI', 'Wishlist')], default='AV', max_length=2),
        ),
    ]
