# Generated by Django 4.1.4 on 2023-03-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_travels', '0009_places_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistsForPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('item_done', models.BooleanField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_travels.places')),
            ],
        ),
    ]
