# Generated by Django 4.1.4 on 2023-03-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_travels', '0010_checklistsforplaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistsforplaces',
            name='item_done',
            field=models.BooleanField(default=False),
        ),
    ]
