# Generated by Django 4.1.4 on 2023-03-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_travels', '0012_items_lists_delete_checklistsforplaces_items_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='place_id',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Lists',
        ),
    ]
