# Generated by Django 4.1.4 on 2023-04-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_travels', '0013_remove_lists_place_id_delete_items_delete_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('place', models.ManyToManyField(to='my_travels.places')),
            ],
        ),
    ]
