# Generated by Django 4.1.4 on 2023-04-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_travels', '0014_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='place',
        ),
        migrations.AddField(
            model_name='places',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='my_travels.tag'),
        ),
    ]
