# Generated by Django 4.1.4 on 2023-04-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_travels', '0016_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='tag',
            field=models.ManyToManyField(blank=True, to='my_travels.tag'),
        ),
    ]
