# Generated by Django 4.1.4 on 2023-08-26 07:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_travels', '0017_alter_places_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
