# Generated by Django 4.1.4 on 2023-03-31 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_travels', '0013_remove_lists_place_id_delete_items_delete_lists'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='place_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_travels.places'),
        ),
    ]
